### ISSUE TITLE
create meter telemetry schema

### ISSUE THREAD

**Issue by malikmayank** [slacgismo/TESS#11]
Holy Cross Energy will provide meter data in [this format](/master/docs/datafile-samples/RateStudy15MinKwn20200224.csv). Create an RDS MySQL table to store meter telemetry.

**Comment by dchassin** [comment]
Here is the Olympic report for Anna:  https://www.pnnl.gov/main/publications/external/technical_reports/PNNL-17167.pdf

On Mar 12, 2020, at 13:07, Mayank Malik <notifications@github.com> wrote:

﻿

Closed #11<https://github.com/slacgismo/TESS/issues/11> via #17<https://github.com/slacgismo/TESS/pull/17>.
