### ISSUE TITLE
Error running npx for mobile app

### ISSUE THREAD

**Issue by dchassin** [slacgismo/TESS#7]
After entering the following command according the `mobile/README.md`, an error occurs:
~~~
bash$ npx react-natice run-ios
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-natice - Not found
npm ERR! 404 
npm ERR! 404  'react-natice@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dchassin/.npm/_logs/2020-02-12T22_58_31_299Z-debug.log
Install for [ 'react-natice@latest' ] failed with code 1
~~~

**Comment by jongoncalves** [comment]
You misspelled `react-native`. Can you please re-verify and close this.

**Comment by dchassin** [comment]
Sorry. Wrong error:
~~~
bash$ npx react-native run-ios
info Found Xcode workspace "tess.xcworkspace"
xcrun: error: unable to find utility "simctl", not a developer tool or in PATH
error Could not parse the simulator list output. Run CLI with --verbose flag for more details.
~~~

**Comment by jongoncalves** [comment]
Hummmm, interesting. Do you have the latest version of xcode installed?

Can you try a couple of the suggestions here and let me know if it works:
https://stackoverflow.com/questions/29108172/xcrun-unable-to-find-simctl

**Comment by dchassin** [comment]
I just installed Xcode today. The suggestion to open Xcode->Preferences->Locations and set the Command Line Tools field to something worked. The simulator now opens but I get the following error:
~~~
bash$ npx react-native run-ios
info Found Xcode workspace "tess.xcworkspace"
info Launching iPhone 11 (iOS 13.3)
info Building (using "xcodebuild -workspace tess.xcworkspace -configuration Debug -scheme tess -destination id=C4C795A5-7037-4565-BDF0-9B349A8751E8 -derivedDataPath build/tess")
..............
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening tess.xcworkspace. Run CLI with --verbose flag for more details.
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/dchassin/github/TESS/mobile/tess/ios/build/tess

note: Using new build system
note: Planning build
note: Constructing build description
error: /Users/dchassin/github/TESS/mobile/tess/ios/Pods/Target Support Files/Pods-tess/Pods-tess.debug.xcconfig: unable to open file (in target "tess" in project "tess") (in target 'tess' from project 'tess')
error: /Users/dchassin/github/TESS/mobile/tess/ios/Pods/Target Support Files/Pods-tess/Pods-tess.debug.xcconfig: unable to open file (in target "tess" in project "tess") (in target 'tess' from project 'tess')
error: /Users/dchassin/github/TESS/mobile/tess/ios/Pods/Target Support Files/Pods-tess/Pods-tess.debug.xcconfig: unable to open file (in target "tess" in project "tess") (in target 'tess' from project 'tess')
error: /Users/dchassin/github/TESS/mobile/tess/ios/Pods/Target Support Files/Pods-tess/Pods-tess.debug.xcconfig: unable to open file (in target "tess" in project "tess") (in target 'tess' from project 'tess')
warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the tess editor. (in target 'tess' from project 'tess')
error: /Users/dchassin/github/TESS/mobile/tess/ios/Pods/Target Support Files/Pods-tessTests/Pods-tessTests.debug.xcconfig: unable to open file (in target "tessTests" in project "tess") (in target 'tessTests' from project 'tess')
error: /Users/dchassin/github/TESS/mobile/tess/ios/Pods/Target Support Files/Pods-tessTests/Pods-tessTests.debug.xcconfig: unable to open file (in target "tessTests" in project "tess") (in target 'tessTests' from project 'tess')
error: /Users/dchassin/github/TESS/mobile/tess/ios/Pods/Target Support Files/Pods-tessTests/Pods-tessTests.debug.xcconfig: unable to open file (in target "tessTests" in project "tess") (in target 'tessTests' from project 'tess')
error: /Users/dchassin/github/TESS/mobile/tess/ios/Pods/Target Support Files/Pods-tessTests/Pods-tessTests.debug.xcconfig: unable to open file (in target "tessTests" in project "tess") (in target 'tessTests' from project 'tess')

** BUILD FAILED **
~~~
Sorry about being such a pest.

**Comment by dchassin** [comment]
The android one fails too.  Not sure whether it's the same problem.
~~~
bash$ npx react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 968 file(s) to forward-jetify. Using 12 workers...
info Starting JS server...
/bin/sh: adb: command not found
info Launching emulator...
error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...
Downloading https://services.gradle.org/distributions/gradle-5.5-all.zip
.................................................................................................................................

Welcome to Gradle 5.5!

Here are the highlights of this release:
 - Kickstart Gradle plugin development with gradle init
 - Distribute organization-wide Gradle properties in custom Gradle distributions
 - Transform dependency artifacts on resolution

For more details see https://docs.gradle.org/5.5/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':@react-native-community_async-storage'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/dchassin/github/TESS/mobile/tess/android/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':@react-native-community_async-storage'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/dchassin/github/TESS/mobile/tess/android/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s

    at checkExecSyncError (child_process.js:611:11)
    at execFileSync (child_process.js:629:15)
    at runOnAllDevices (/Users/dchassin/github/TESS/mobile/tess/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
~~~

**Comment by jongoncalves** [comment]
> I just installed Xcode today. The suggestion to open Xcode->Preferences->Locations and set the Command Line Tools field to something worked. The simulator now opens but I get the following error:
> 
> ```
> bash$ npx react-native run-ios
> info Found Xcode workspace "tess.xcworkspace"
> info Launching iPhone 11 (iOS 13.3)
> info Building (using "xcodebuild -workspace tess.xcworkspace -configuration Debug -scheme tess -destination id=C4C795A5-7037-4565-BDF0-9B349A8751E8 -derivedDataPath build/tess")
> ..............
> error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening tess.xcworkspace. Run CLI with --verbose flag for more details.
> User defaults from command line:
>     IDEDerivedDataPathOverride = /Users/dchassin/github/TESS/mobile/tess/ios/build/tess
> 
> note: Using new build system
> note: Planning build
> note: Constructing build description
> error: /Users/dchassin/github/TESS/mobile/tess/ios/Pods/Target Support Files/Pods-tess/Pods-tess.debug.xcconfig: unable to open file (in target "tess" in project "tess") (in target 'tess' from project 'tess')
> error: /Users/dchassin/github/TESS/mobile/tess/ios/Pods/Target Support Files/Pods-tess/Pods-tess.debug.xcconfig: unable to open file (in target "tess" in project "tess") (in target 'tess' from project 'tess')
> error: /Users/dchassin/github/TESS/mobile/tess/ios/Pods/Target Support Files/Pods-tess/Pods-tess.debug.xcconfig: unable to open file (in target "tess" in project "tess") (in target 'tess' from project 'tess')
> error: /Users/dchassin/github/TESS/mobile/tess/ios/Pods/Target Support Files/Pods-tess/Pods-tess.debug.xcconfig: unable to open file (in target "tess" in project "tess") (in target 'tess' from project 'tess')
> warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the tess editor. (in target 'tess' from project 'tess')
> error: /Users/dchassin/github/TESS/mobile/tess/ios/Pods/Target Support Files/Pods-tessTests/Pods-tessTests.debug.xcconfig: unable to open file (in target "tessTests" in project "tess") (in target 'tessTests' from project 'tess')
> error: /Users/dchassin/github/TESS/mobile/tess/ios/Pods/Target Support Files/Pods-tessTests/Pods-tessTests.debug.xcconfig: unable to open file (in target "tessTests" in project "tess") (in target 'tessTests' from project 'tess')
> error: /Users/dchassin/github/TESS/mobile/tess/ios/Pods/Target Support Files/Pods-tessTests/Pods-tessTests.debug.xcconfig: unable to open file (in target "tessTests" in project "tess") (in target 'tessTests' from project 'tess')
> error: /Users/dchassin/github/TESS/mobile/tess/ios/Pods/Target Support Files/Pods-tessTests/Pods-tessTests.debug.xcconfig: unable to open file (in target "tessTests" in project "tess") (in target 'tessTests' from project 'tess')
> 
> ** BUILD FAILED **
> ```
> 
> Sorry about being such a pest.

Can you verify that your pods are installed? They seem to be missing from I can tell in that error message

**Comment by jongoncalves** [comment]
> The android one fails too. Not sure whether it's the same problem.
> 
> ```
> bash$ npx react-native run-android
> info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
> Jetifier found 968 file(s) to forward-jetify. Using 12 workers...
> info Starting JS server...
> /bin/sh: adb: command not found
> info Launching emulator...
> error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
> warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
> info Installing the app...
> Downloading https://services.gradle.org/distributions/gradle-5.5-all.zip
> .................................................................................................................................
> 
> Welcome to Gradle 5.5!
> 
> Here are the highlights of this release:
>  - Kickstart Gradle plugin development with gradle init
>  - Distribute organization-wide Gradle properties in custom Gradle distributions
>  - Transform dependency artifacts on resolution
> 
> For more details see https://docs.gradle.org/5.5/release-notes.html
> 
> Starting a Gradle Daemon (subsequent builds will be faster)
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':@react-native-community_async-storage'.
> > SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/dchassin/github/TESS/mobile/tess/android/local.properties'.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 31s
> 
> error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
> Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':@react-native-community_async-storage'.
> > SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/dchassin/github/TESS/mobile/tess/android/local.properties'.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 31s
> 
>     at checkExecSyncError (child_process.js:611:11)
>     at execFileSync (child_process.js:629:15)
>     at runOnAllDevices (/Users/dchassin/github/TESS/mobile/tess/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> ```

There are two things that come to mind to check, did your node modules install and is the Android Sim running? For android, the instructions imply a lot. One of which is that you need to start the simulator manually; unfortunately the react-native CLI can't do it for us like it does for iOS.

**Comment by dchassin** [comment]
For iOS I reinstalled pods and it works now. (I'm not sure why it didn't work the first time.)  

For android, I don't know how to start the sim manually.

**Comment by dchassin** [comment]
I assume that it's expected at this point that only the first two screens welcome pages come up.  It doesn't do anything after I click "I Agree".

**Comment by jongoncalves** [comment]
> For iOS I reinstalled pods and it works now. (I'm not sure why it didn't work the first time.)
> 
> For android, I don't know how to start the sim manually.

Google will likely be your best friend on this one. Or maybe later I can sit down with you to do it, but there are a lot of steps. The gist however > Launch Android Studio > Launch its Android Device Manager > Follow the creation wizard to create a new Android virtual device > I chose a Pixel 3 device with android 9 running > download and install all the required packages it tells you to > once successful, launch the device (press the play button) > then run `react-native run-android`

**Comment by jongoncalves** [comment]
> I assume that it's expected at this point that only the first two screens welcome pages come up. It doesn't do anything after I click "I Agree".

Correct, not all the pages are there yet....my current pace is about one non-styled page every 1.5 days. I'm hopeful my pace will pick up once I finish fixing foundational things. But that's being optimistic....My pace may actually slow down due to page complexity and integration with resources over the wire, i.e. a backend; API; etc...

**Comment by dchassin** [comment]
Ok. No problem. Can we provide either a list of steps or a pointer to instructions for Android?

FYI, there are some issues with the Hejla controllers that may significantly affect how/where the backend is deployed that may in turn affect the mobile and control room front-ends.  @malikmayank will brief us today.
